### ISSUE TITLE
Rate My Paul No Longer Works After July 1st Update

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#104]
This is a big problem. They have just updated campus connect and the extension no longer works. We need to urgently fix this and push out the fix. I will look at this when I get home tonight.

**Comment by computerfr33k** [comment]
Did they get rid of iframes?

**Comment by SergueiFedorov** [comment]
Looks like main() is no longer getting called

**Comment by SergueiFedorov** [comment]
Looks like getting rid of jQuery(window).load(function () ... seems to get things working. However, there appears to be other issues like:

Uncaught ReferenceError: showUpdateNotificationIfNecessary is not defined

**Comment by SergueiFedorov** [comment]
jQuery.fn.jquery returns version 1.6.2. It seems to be colliding with the version of jQuery we are using. We are using version 2.1.3. This might be what is creating issues because things like events are not binding to the DOM elements properly. The $("body").on("click", ".ratingButton", function () is no longer trigger, nor is jQuery(window).load(function ()

**Comment by SergueiFedorov** [comment]
This has been resolved in 1.6.1 which I pushed out to the store.
