### ISSUE TITLE
Sometimes the extension does not start

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#11]
I don't have very many details about this, so I am creating this to be able to append to it.

From time to time I notice the plugin doesn't start up. I will be on the lookout for error codes and what not in the chrome console when it happens again.

**Comment by computerfr33k** [comment]
I notice this when "reloading" the plugin. Could be something to do with how chrome handles reloading plugins? Not sure if there is a function that needs to be implemented for it or not.

**Comment by SergueiFedorov** [comment]
I think you are right. It seems to happen when you reload the plugin. I haven't see this issue in any other context. I am closing this.
