### ISSUE TITLE
Make popup pinnable(static)

### ISSUE THREAD

**Issue by ochagata** [ochagata/rateMyPaul#15]
As a user, I want to be able to "Pin" the popup in case I'm navigating to a different page of the search to compare professors
Also, as a user I want to be able to "Pin" the current popup and when I press "Show Ratings", unless the professor ratings are already "pinned", it will add another box

**Comment by SergueiFedorov** [comment]
After release

**Comment by SergueiFedorov** [comment]
You can pin the pupup now. I till not disappear when you pin it and navigate to other pages.
