### ISSUE TITLE
PHP Webservice

### ISSUE THREAD

**Issue by computerfr33k** [ochagata/rateMyPaul#22]
Any Ideas why my PHP service doesn't work properly with the extension?
I made sure it returned the same as the one surgei made. Maybe something I'm missing?

https://github.com/computerfr33k/RateMyPaulWebService/tree/php-development

the urls i used are:
http://ssh.pltw-racine.org/RMP/Professor.php?url=
http://ssh.pltw-racine.org/RMP/search

**Comment by SergueiFedorov** [comment]
I can't tell from just looking at your code. I haven't worked with PHP in a long time.

One thing you could try is:

echo json_encode($result)

to see what happens. I should be seeing an empty JSON object if nothing is returned. Right now it's just blank (I have added the URL portion)

**Comment by computerfr33k** [comment]
weird thing is, the extension is getting the data, but I keep getting this error:

Uncaught TypeError: Cannot read property '0' of undefinedPopupFunctionality.js:66 (anonymous function)
jquery-2.1.3.min.js:2 n.Callbacks.jjquery-2.1.3.min.js:2 n.Callbacks.k.fireWithjquery-2.1.3.min.js:4 xjquery-2.1.3.min.js:4 n.ajaxTransport.k.cors.a.crossDomain.send.b

**Comment by computerfr33k** [comment]
Doh, I figured out why. LOL

I had the second array named Results instead of Ratings.
