### ISSUE TITLE
If overall quality is absent on RMP popup fails

### ISSUE THREAD

**Issue by ochagata** [ochagata/rateMyPaul#23]
![image](https://cloud.githubusercontent.com/assets/4699540/6887954/1b4afc0c-d634-11e4-96fa-b367628597a7.png)

**Comment by SergueiFedorov** [comment]
Can you grab the response JSON string?

**Comment by SergueiFedorov** [comment]
Fixed. It was an exception with the webservice. I added a unit test and accounted for the edge case.
