### ISSUE TITLE
Chrome Extention Requiring Access To Browser History

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#26]
The plugin does not use anything related to browser history. But for some reason it is asking for access to browser history access. Something in the manifest needs to be fixed. I have no idea what is causing it.

**Comment by computerfr33k** [comment]
This is because of the "Tabs" Permission.
https://developer.chrome.com/extensions/permission_warnings

**Comment by SergueiFedorov** [comment]
Good catch! If you can put in the fix that would be great. Looks like we have "Tabs" under the "Permissions" section in the manifest.

**Comment by computerfr33k** [comment]
This is a bummer.

> The URL the tab is displaying. This property is only present if the extension's manifest includes the "tabs" permission.

**Comment by SergueiFedorov** [comment]
This has been fixed.

**Comment by computerfr33k** [comment]
We actually need this permission because the extension needs to be able to access the tab's url. Extension won't currently function without it.

**Comment by SergueiFedorov** [comment]
The extension triggers when it hits any of URLs provided in the manifest. I don't think we do any URL parsing. Is there a specific line that fails when you remove "tabs" out of the manifest?

**Comment by computerfr33k** [comment]
https://github.com/ochagata/rateMyPaul/blob/dev/eventPage.js#L3

**Comment by ochagata** [comment]
That doesn't do anything essential to the extension itself

**Comment by SergueiFedorov** [comment]
I haven't even looked at that code file for a long time. Does it even do anything at this point? Good catch you Eric.

**Comment by ochagata** [comment]
Nope

**Comment by SergueiFedorov** [comment]
You can remove it Eric.

**Comment by computerfr33k** [comment]
that file causes the extension to fail to load since it is declared as a script in manifest
