### ISSUE TITLE
WebService Mirrors

### ISSUE THREAD

**Issue by computerfr33k** [ochagata/rateMyPaul#29]
Something that could be useful is to allow mirrors, so if a server goes offline the user could select another one or automatically switch or possibly supply their own.

**Comment by SergueiFedorov** [comment]
Yes it would be useful. However, once it scales to something like that I think we would consider moving to a cloud hosting service like Azure. I am working on speeding up the page parsing but parsing strings is an uphill battle.

For right now I think we need to run a benchmark to see where the current web host tops out on requests. Then we can contrast that against actual request statistics and see if it's worth considering a backup plan.

As for right now our user base is very slow, but hopefully it will grow. It's a little early to consider this question but it might become important in the future.
