### ISSUE TITLE
Repeated professor name handling

### ISSUE THREAD

**Issue by ochagata** [ochagata/rateMyPaul#3]
Some classes have multiple professors teaching them

**Comment by SergueiFedorov** [comment]
I don't understand the issue. What happens when there are multiple professors teaching a class?

**Comment by SergueiFedorov** [comment]
Poke. Please give me a screenshot or a professor name to test against

**Comment by ochagata** [comment]
![screen shot 2015-03-31 at 12 19 12 pm](https://cloud.githubusercontent.com/assets/4699540/6924733/34663626-d7a0-11e4-9b0f-e06ccdee6f19.png)

**Comment by ochagata** [comment]
![screen shot 2015-03-31 at 12 21 18 pm](https://cloud.githubusercontent.com/assets/4699540/6924772/7b036266-d7a0-11e4-859b-c1177fa3faf3.png)

**Comment by SergueiFedorov** [comment]
lol why is it formatted like that in Campus Connect? I'll fix it but damn that is kind of broken.

**Comment by computerfr33k** [comment]
Because Campus Connect is great software..LOL

**Comment by ochagata** [comment]
But anyways, we just need it to be smart, use one instance of a repeated name, and idk how to handle the other one

**Comment by SergueiFedorov** [comment]
If a name has more than one space, it basically means it's a repeat. I have never seen a name with 3 spaces (say a middle name).

**Comment by SergueiFedorov** [comment]
It will take the first name it finds. The rest of the names are ignored.

**Comment by ochagata** [comment]
What if there are 2 different professors?

**Comment by SergueiFedorov** [comment]
I considered that, but didn't get to it. What should happen if there is? Should it open multiple popups?

**Comment by ochagata** [comment]
Yeah, I was thinking about multiple popups

**Comment by SergueiFedorov** [comment]
Hmmm. Reopen a ticket onto that specific issue. This one was about handling repeats of professors (at least it became that).

I will need to figure out a way to open multiple popups side by side
