### ISSUE TITLE
WebService Build/Version Number In Popup

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#32]
We should probably, in addition to having a link to the chrome extension page, should add the version number of the web service at the bottom. The issue is that the extension and webservice are disjointed, so if people have issues we can ask for the version number they are seeing.

**Comment by ochagata** [comment]
We can add an i inside an O that opens a tooltip when hovered over

**Comment by SergueiFedorov** [comment]
I like that idea!

**Comment by SergueiFedorov** [comment]
Obsolete
