### ISSUE TITLE
Add a "Search" function to the popup

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#33]
It might be useful to have a search button at the top that let's the user enter the name of the professor manually.

**Comment by computerfr33k** [comment]
I started an initial version of this, but can't figure out how to make my JS file be able to use the functions from the other JS files in the extension.

https://github.com/computerfr33k/rateMyPaul/blob/issue-33/search.js

**Comment by SergueiFedorov** [comment]
Make sure that the search.js is included in the manifest. Process search results is probably scoped a function:

        (function() { [..] })();

I actually beat you to the implementation. Take a look at what I committed today and see if you can make use of any of that.

**Comment by SergueiFedorov** [comment]
I just realized what I said doesn't make too much sense. There are a lot of scoped functions in main.js. So:

     (function() {
              function ProcessSearchResults(response, popupDelegate, professorName) {
                         [..]
              }
     }

is not visible from outside. If you want a function to be visible from outside, move the 

      (function() { } )();

 outside the scoping function.

**Comment by SergueiFedorov** [comment]
What is the status on this? We have a release planned for tomorrow (I'll fix the releases section in a little bit)

**Comment by computerfr33k** [comment]
I've been frustrated with how I originally wanted to do it, but I am working on my plan B. I'll show you once I get the general stuff done. Just looking up some jquery things for it too. But, I am planning on making it in the popup (when you click on the extension icon in the address bar).

**Comment by SergueiFedorov** [comment]
The extension supports multiple popups now. I am not sure how you can build
in the search into the actual popup.

**Comment by computerfr33k** [comment]
Take a look at this and tell me if this would be good for a user.
https://github.com/computerfr33k/rateMyPaul/tree/issue-33

**Comment by SergueiFedorov** [comment]
I don't see a search bar in the issue-33 branch. Did I do something wrong?

**Comment by computerfr33k** [comment]
Did u click on the icon? Because it works for me.

On April 5, 2015 11:52:43 AM CDT, Serguei Fedorov <notifications@github.com> wrote:
>I don't see a search bar in the issue-33 branch. Did I do something
>wrong?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ochagata/rateMyPaul/issues/33#issuecomment-89809602

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SergueiFedorov** [comment]
![image](https://cloud.githubusercontent.com/assets/3649629/6997985/11640d60-db97-11e4-8f29-429ba081fd63.png)

**Comment by SergueiFedorov** [comment]
Ok now that you showed me I totally get what you are doing. Just make sure the user knows that the functionality is there.

**Comment by ochagata** [comment]
@computerfr33k
Bump
