### ISSUE TITLE
Show Overall Professor Rating Next to Their Name

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#50]
This might be something useful. It can be the overall rating (like say A+) and the user can click on "show ratings" for more information.

The only problem is logistical, considering it will vastly increase the traffic to the web service.

**Comment by ochagata** [comment]
Since we no longer have a web service, should we try this? @SergueiFedorov 
Bump

**Comment by SergueiFedorov** [comment]
I am not sure how possible this is. Because for every professor we need to do a request. I'll try and prototype this, but it might be quite expensive to compute

**Comment by ochagata** [comment]
Yeah, I feel like while it would be a nice feature, it would be too taxing in terms of time

**Comment by SergueiFedorov** [comment]
Let me try the implementation and see what the performance is like.

**Comment by SergueiFedorov** [comment]
This works very well. Since the request is ansync, it pulls in the ratings one by one. It's a cascading effect, but it works

**Comment by SergueiFedorov** [comment]
Done. Mixed with with the cache system it is pretty fast.
