### ISSUE TITLE
GET Request Fails For Images

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#54]
I cannot hunt down why this is happening, though it has not effect for the end user. Chrome for some reason is pulling the images of RMP and tries to open them relative to campus connect. It seems to be an internal behavior.

The end user is not affected by this and this does not create issues for the chrome extension. However an error message does popup in the console.

**Comment by SergueiFedorov** [comment]
Eric can you take a look at this when you get the chance to?

**Comment by SergueiFedorov** [comment]
Error: 
GET https://campusconnect.depaul.edu/assets/ok.png 404 (Not Found)

**Comment by computerfr33k** [comment]
Yea. I've been busy with classes lately. I can look in a bit

On April 10, 2015 5:21:24 PM CDT, Serguei Fedorov <notifications@github.com> wrote:
>Eric can you take a look at this when you get the chance to?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ochagata/rateMyPaul/issues/54#issuecomment-91707507

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SergueiFedorov** [comment]
There is no hurry on this one

**Comment by computerfr33k** [comment]
Where are you seeing this error? Im not seeing it.
![screenshot from 2015-04-10 18-21-28](https://cloud.githubusercontent.com/assets/2096910/7098926/914eb9d8-dfae-11e4-88a3-4045d2ba7697.png)

**Comment by SergueiFedorov** [comment]
I think the pull request is still open, which @ochagata has to merge. Clone by dev branch, it should be in there.

**Comment by computerfr33k** [comment]
PopupFunctionality.js
line 139: $(".RMPDisplayArea").draggable();
I'm not sure why, but this function causes the GET request.

**Comment by SergueiFedorov** [comment]
That is really odd... are there any options that prevent it from doing that?

**Comment by computerfr33k** [comment]
wait, nevermind. I guess it only does it the first time you click on someone.

**Comment by computerfr33k** [comment]
Okay, I think that this may be coming from the RMPParser.js

**Comment by computerfr33k** [comment]
Here's what I did for blocking the request to the RMP images being request from campusconnect

```
chrome.webRequest.onBeforeRequest.addListener(
        function(details) { return {cancel: true}; },
        {urls: ["*://campusconnect.depaul.edu/*/assets/chilis/cold-chili.png"]},
        ["blocking"]);
```

**Comment by SergueiFedorov** [comment]
Awesome! Thanks for looking into this. Push request it into the main depo. I am about to start messing with the project structure so it would be good to merge thing is before then

**Comment by SergueiFedorov** [comment]
Is this fixed? Can we close this one?
