### ISSUE TITLE
Recent Push to Dev

### ISSUE THREAD

**Issue by computerfr33k** [ochagata/rateMyPaul#57]
There are some missing files from the recent push to Dev branch. Extension isn't loadable right now

**Comment by ochagata** [comment]
What files?

**Comment by SergueiFedorov** [comment]
I've noticed that the lock icon is missing. Is something else missing?

**Comment by computerfr33k** [comment]
jquery-ui stuff Utilities.js and maybe some others.

**Comment by SergueiFedorov** [comment]
I'll take a look at in 15ish min when I get home

**Comment by SergueiFedorov** [comment]
@ochagata 
https://github.com/ochagata/rateMyPaul/commit/45dcee327220ea036779a5da4c15da50c76ff836
