### ISSUE TITLE
Make reviews and rating drop-downs inside popup closeable

### ISSUE THREAD

**Issue by ochagata** [ochagata/rateMyPaul#58]
If clicked when open, it should close.
And only one can be open at a time

**Comment by SergueiFedorov** [comment]
That reviews and ratings are an accordion panel which expands and contracts depending on what you are looking at. I don't understand this issue...

**Comment by SergueiFedorov** [comment]
Ooops, I didn't realize I can't assign multiple people. Either of you please look into it!

**Comment by ochagata** [comment]
The issue is that one drop-down is always open
Make it so that if a drop-down is open, when you click it, it closes
But only one can be open at a time

**Comment by SergueiFedorov** [comment]
![image](https://cloud.githubusercontent.com/assets/3649629/7190310/d0a9640c-e44a-11e4-811f-f2458b40ec47.png)

**Comment by ochagata** [comment]
Yes
