### ISSUE TITLE
Abstract GET Request Code

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#62]
The GET request code is unique to Firefox and Chrome. We need to wrap this into an agnostic layer so that we don't litter the central code base with GET requests for HTML templates and RMP pages.

**Comment by computerfr33k** [comment]
what about JQuery Ajax?

**Comment by SergueiFedorov** [comment]
The problem I ran into with that is that because RMP is not Https, Chrome does not allow requests from the page from a page that is HTTPs to a non secure HTTP domain. Normal Ajax requests are blocked because of that. As a result, we use their messaging routine so that it's Chrome requesting the page internally as not as if it's the page. I haven't tried normal Ajax with Firefox, but I imagine it's going to block it just like Chrome

**Comment by computerfr33k** [comment]
using JQuery $.get(); does work in chrome extension because we have the permissions set to access the urls in the manifest. I actually rewrote your RMP.js using this jquery.get

**Comment by SergueiFedorov** [comment]
Cool, that should make things a lot simpler for cross browser compatibility. I remember Ozy and I couldn't figure it out, so thanks for looking into this!

**Comment by SergueiFedorov** [comment]
I am getting the following error:

Mixed Content: The page at 'https://campusconnect.depaul.edu/psc/CSPRD90/EMPLOYEE/HRMS/c/COMMUNITY_ACCE…du%2fpsc%2fCSPRD90%2f&PortalHostNode=HRMS&NoCrumbs=yes&PortalKeyStruct=yes' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.ratemyprofessors.com/search.jsp?queryoption=HEADER&queryBy=teacherName&schoolName=DePaul+University&schoolID=1389&query=Jessica%20Larva'. This request has been blocked; the content must be served over HTTPS.
