### ISSUE TITLE
Search Function Not Working

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#69]
The search function is not working for me. When I click "Search" nothing happens

**Comment by computerfr33k** [comment]
works for me: 
![screenshot from 2015-04-20 18-52-12](https://cloud.githubusercontent.com/assets/2096910/7243043/9ddeaf04-e78e-11e4-8566-4f6b71c95dd9.png)

**Comment by SergueiFedorov** [comment]
Please checkout the last pull request

**Comment by SergueiFedorov** [comment]
This works. I just didn't get any feedback on an empty search. I added:


        if (data.length == 0)
        {
            $('#ErrorLog').text("Search did not produce any results.");
            $('#ErrorLog').show();
            return;
        }

to make sure the user gets feedback on what is going on
