### ISSUE TITLE
Popup always grabs data from Lawrence Gluck

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#70]
The popup is always grabbing data specifically for Lawrence Gluck. No matter which professor I select.

**Comment by SergueiFedorov** [comment]
Fixed. It was a bug I created myself.

**Comment by computerfr33k** [comment]
I fixed this with the latest commit. I hadn't added a check for an empty input

**Comment by SergueiFedorov** [comment]
It wasn't an empty string issue. It was an issue where it was submitting the wrong string into the professor search field.

**Comment by computerfr33k** [comment]
Do you know how this was happening? or what was being submitted?

**Comment by SergueiFedorov** [comment]
I merged your changes in. It was not for the search, but rather for the "Show Ratings" button. Basically it was submitting an empty string because I appended the wrong variable onto it. It was a similar issue to yours, but it was linked to the button code
