### ISSUE TITLE
Make the search function less platform specific

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#72]
I think it would be useful for porting into other browsers, if the search function was not tied to the extension logo in Chrome. That way it would be much simpler to port and maintain that functionality between browser platforms

**Comment by computerfr33k** [comment]
the search_popup files aren't platform specific, they are shown when clicking on the logo because I defined it in the chrome manifest.
```json
// this executes the html file when clicking on the icon
"page_action": {
          "default_icon": "icon.png",
          "default_popup": "search_popup.html"
      },
```

Or do you mean something else.

**Comment by SergueiFedorov** [comment]
Oh I see it now. I'm porting everything into Firefox (using the new structure) tonight, so I will let you know how easily it will port over.
