### ISSUE TITLE
Add local cache for professor info

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#73]
Since we are pulling all professor names and data on the page, it would be useful to cache the names locally into an object. So it would be:

      CacheObjects = {};
      CacheObject["FacultyName"] = FullFacultyRecord;

Instead of pulling and parsing the info every single time, it will grab the cache record if it exists

**Comment by computerfr33k** [comment]
Do you know if it is possible to check the timestamp for the webpage. because then you could use persistent caching and just check timestamp of the page with the local cache.
https://developer.chrome.com/extensions/storage

**Comment by SergueiFedorov** [comment]
Thanks for the link. Interesting. I'll have to get back to you on that! But yes, using the native browser storage is smart... we could just have an object which is:

       CachedObject.InsertTime
       CachedObject.FacultyName
       CachedObject.Data //Holds the JSON parsed from the RMPParser

Once the:

      CurrentTime - CacheObject.InsertTime

expires, we can request a recache

**Comment by computerfr33k** [comment]
RMP has a cache-control header, which we could use to determine how long to cache for. not sure how to fetch that info using js

**Comment by SergueiFedorov** [comment]
Hmm. The problem with that is that we would need to fetch that for every request which makes the local caching system redundant (we might as well reparse the page since we loaded the HTML)

**Comment by computerfr33k** [comment]
you could save the timestamp in local storage. and check that before the request.
http://stackoverflow.com/questions/220231/accessing-the-web-pages-http-headers-in-javascript

**Comment by SergueiFedorov** [comment]
Let me try to implement it this way first. This seems a little more simple. Then we can look into making it more accurate. I like your idea, but I think we can save some time on just using Date.Now() as the time stamp. Once I get that working, I will looking to parsing out the timestamp of the header.

**Comment by computerfr33k** [comment]
yea.

pseduo-code of my idea

```javascript
function CreateGetRequst(source_url, callback) {
	chrome.localstorage.get(source_url, function(data) {
		if(data.timestamp > currentDate) {
			// use cached data
		} else {
			// fetch data from RMP
		}
	}
}
```

**Comment by SergueiFedorov** [comment]
I got this working at the moment without tapping into Chrome's native API

function Cache()
{
	var CacheTable = {};

	this.RecordExists = function(FacultyName)
	{
		if (FacultyName in CacheTable)
		{
			var CacheExpiration = new Date();
			CacheExpiration.setHours(12);

			if (Date.now() - CacheTable[FacultyName] > CacheExpiration)
			{
				return false;
			}

			return true;
		}

		return false;
	};

	this.GetRecord = function(FacultyName)
	{
		return CacheTable[FacultyName];
	};

	this.InsertRecord = function(FacultyName, data)
	{
		CacheObject = {};
		CacheObject.InsertTime = Date.now();
		CacheObject.FacultyName = FacultyName;
		CacheObject.Data = data;

		CacheTable[FacultyName] = CacheObject;
	};
}

**Comment by SergueiFedorov** [comment]
It works, so I am moving onto using Chromes local storage

**Comment by SergueiFedorov** [comment]
The cache is implemented using the Chrome API. The code is:

       function Cache()
       {
	       this.GetRecord = function(FacultyName, callback)
	       {
		       chrome.storage.local.get(FacultyName, function(result)
		       {
			       callback(result[FacultyName]);
		       });
	       };

	       this.InsertRecord = function(FacultyName, data)
	       {
		       var CacheObject = {};
		       CacheObject.InsertTime = Date.now();
		       CacheObject.Data = data;

		       var SaveObject = {};
		       SaveObject[FacultyName] = CacheObject;

		       chrome.storage.local.set(SaveObject);
	       };
       }
