### ISSUE TITLE
Basic Webpage For SEO

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#77]
We have been denied a request to host a promotion table at DePaul. I will see what I can do about it, but as of right now we need a basic web page to redirect users to our extension and provide some basic information. Right now the search:

      Rate My Paul

Comes up empty because everything we have is RateMyPaul. This can be an issue, because people will naturally insert spaces into the name.

A website with proper SEO will help with this.

**Comment by computerfr33k** [comment]
I am assuming that you submitted this?
https://addons.mozilla.org/en-US/firefox/addon/ratemypaul/

**Comment by SergueiFedorov** [comment]
Yes that was before we started restructuring things in the project. There are a few fixes that need to be done to it (such as only supporting the latest FireFox version), but overall it's in working condition. I have been holding off announcing it until we release 2.0

**Comment by computerfr33k** [comment]
What about something like this? http://www.computerfr33k.me/rateMyPaul/
We can host it using github-pages, which is where i have this currently

**Comment by SergueiFedorov** [comment]
This works perfectly for now until we can get something more elaborate. Just make sure that google can query the site for

     Rate My Paul

and not just

      RateMyPaul

Make sure to add all our names. Also for the FireFox version, put brackets in that say "Available only with latest version of FireFox". You can replace the FireFox version text with the actual latest FireFox version numbers.

**Comment by SergueiFedorov** [comment]
Also we will need to purchase a domain name

**Comment by computerfr33k** [comment]
Alright, I set up analytics for that page just to see how it performs as is. Then we can tweak it. I added a keywords meta tag so hopefully that helps. Maybe I should pull my gh-pages branch to the main project repo?

**Comment by SergueiFedorov** [comment]
Yea. Just make it a folder called "Website" or something like that

**Comment by SergueiFedorov** [comment]
I'll reopen this when we get around to making a more feature packed website.

**Comment by SergueiFedorov** [comment]
Here is a useful tool that might help with SEO

https://developers.google.com/structured-data/testing-tool/

**Comment by SergueiFedorov** [comment]
We also need to include the meta tags:

RateMyDePaul
Rate My DePaul

because that is what people will type into google looking for our extension

**Comment by computerfr33k** [comment]
Does DePaul offer students webserver space? I COULD throw it on my VPS, but I'm thinking long term just in case I ever discontinue my VPS or something else comes up.

**Comment by SergueiFedorov** [comment]
I have a web hosting account, though it is for Asp.NET. I am sure we can get a really cheap one if we need it.

**Comment by computerfr33k** [comment]
Mainly Because I was thinking of using [Ghost](http://ghost.org). Here's an example: http://ratemypaul.site11.com/

**Comment by SergueiFedorov** [comment]
Is this just a blogging site or does it allow you to create actual HTML pages? (maybe more than that even?)

**Comment by computerfr33k** [comment]
You can always customize the themes, and it uses markdown for the pages so you can always add html or whatever you want that the browser can render. Since the software just takes the content and adds it into an html page. (Static site generator basically)

**Comment by SergueiFedorov** [comment]
Hmmm, that would work. I know this is more work, but I was thinking of something like this:

http://ds4windows.com/

where is presents the software and it's features

**Comment by computerfr33k** [comment]
http://ghostscroll.grmmph.com/

**Comment by SergueiFedorov** [comment]
Yup

**Comment by computerfr33k** [comment]
aight, let me try out that theme

**Comment by SergueiFedorov** [comment]
Also we need an actual domain name

**Comment by computerfr33k** [comment]
What should I add to this site?
https://www.ratemypaul.com/

**Comment by SergueiFedorov** [comment]
Hey, sorry for the delayed response.

I would add a few screen shots and something that  describes what the extension does. It would be a good idea to offer an explanation of the features

**Comment by SergueiFedorov** [comment]
Could you please blur out the names and randomize the text? I don't want us to step on any toes by having actual names up there.

**Comment by computerfr33k** [comment]
Its publicly available though. But I guess.
		
        
		
		 ---- On Fri, 29 May 2015 20:08:35 -0500  notifications@github.com  wrote ----Could you please blur out the names and randomize the text? I don't want us to step on any toes by having actual names up there.

**Comment by SergueiFedorov** [comment]
It is, but I do not want to point out specific faculty as an "example" without their permission. What data is out there that we pull has nothing to do with us. But using someone's name specifically for a promotion can seem as though they gave us endorsement, despite the fact that they did not.

We can reach out to DePaul faculty and see if someone would be willing to give us permission. That way we can use their name/data and not have to blur it out.
