### ISSUE TITLE
Update Message Covers The Native "Loading" icon in CC

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#82]
Just a small fix. The message covers up the spinning loading animation in campus connect

![image](https://cloud.githubusercontent.com/assets/3649629/7290765/58cf0bbc-e94a-11e4-98d8-28cdff20de1c.png)

We should move it a bit lower or to the side a little bit

**Comment by computerfr33k** [comment]
ah, thanks for noticing. I will fix this tomorrow.

**Comment by SergueiFedorov** [comment]
Just scoot it over down and over to the left a little bit so that the spinning loading icon isn't covered

**Comment by computerfr33k** [comment]
fixed in #84
