### ISSUE TITLE
Toastr message no longer showing

### ISSUE THREAD

**Issue by computerfr33k** [ochagata/rateMyPaul#86]
SO, for some reason the toast message no longer shows up for me because it's saying that the object is not defined. Not sure what's changed that is causing this. Is it just me?

**Comment by SergueiFedorov** [comment]
Which object is not defined? I tested it last night before doing the pull
request. Maybe something broke?

**Comment by computerfr33k** [comment]
something broke on my end. I think it might have been when I merged. But i did notice that on Official Dev the toastr appeared twice
