### ISSUE TITLE
Message Displays Any Time Page is Reloaded

### ISSUE THREAD

**Issue by SergueiFedorov** [ochagata/rateMyPaul#88]
This maybe an issue I created. But when I refresh the page entirely, the toast message comes back

**Comment by computerfr33k** [comment]
did you close the toast before refreshing?

**Comment by SergueiFedorov** [comment]
Oh good point. I'll check it out and I'll let you know.

**Comment by computerfr33k** [comment]
Because I currently have it so when you close it, a function runs that then marks it as read.

**Comment by SergueiFedorov** [comment]
I tested it out. I hit the X in the corner and then reload the page. I get the popup again. This is on OS X

**Comment by computerfr33k** [comment]
This is happening because you didn't have the ```js toastr.options.onHidden ``` being set after the main options were being set. So, when you call the toastr.options = {..} in ShowToast the options for onHide is being overwritten.
current workflow:
```js
showUpdateIfNecessary() {
if(show) {
    toastr.options.onHide = function() {}
    ShowToast(..);
}
}

ShowToast() {
    toastr.options = "" //this is setting the options which overrides the onHide since that is a subkey of options.
}
```
